# Generated by Django 4.2.15 on 2024-08-16 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('androidversion_name', models.CharField(max_length=100)),
                ('effective_target_sdk_version', models.CharField(max_length=100)),
                ('md5_code', models.CharField(max_length=500)),
                ('is_black', models.BooleanField(default=False)),
                ('is_signed', models.BooleanField(default=True)),
                ('category', models.CharField(default='正常', max_length=20)),
                ('state', models.CharField(default='特征分析', max_length=20)),
                ('report', models.FileField(null=True, upload_to='documents/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_black', models.BooleanField(default=False)),
                ('apk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apk')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(blank=True, max_length=200, null=True)),
                ('is_danger', models.BooleanField(default=False)),
                ('apk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apk')),
            ],
        ),
        migrations.CreateModel(
            name='Cirtification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('sha1_code', models.CharField(max_length=500)),
                ('sha256_code', models.CharField(max_length=500)),
                ('information', models.CharField(max_length=1000)),
                ('apk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apk')),
            ],
        ),
        migrations.CreateModel(
            name='BlackPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='黑色产业', max_length=20)),
                ('file_path', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='black_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('apk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apk')),
            ],
        ),
    ]
