# Generated by Django 4.2.15 on 2024-08-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_permission_chinese_name_permission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='apk',
            name='conclusion',
            field=models.CharField(default='', max_length=300),
        ),
    ]
