# Generated by Django 4.2.15 on 2024-08-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_apk_code_result_apk_confidence_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='androidversion_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apk',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apk',
            name='effective_target_sdk_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apk',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apk',
            name='state',
            field=models.CharField(default='获取apk', max_length=20),
        ),
    ]
